import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToolkitProvider from "@/components/ToolkitProvider";
import FirebaseProvider from "@/components/FirebaseProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` bg-white`}>
        <ToolkitProvider>
          <FirebaseProvider>
          <div className="w-[85%] mx-auto h-[100vh] flex flex-col ">
            <Navbar />
            <div className="flex-1">{children}</div>
          </div>
          </FirebaseProvider>
        </ToolkitProvider>
      </body>
    </html>
  );
}
